name: Deploy web-sawahlunto to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Execute Remote SSH Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /var/www/kotague
          git pull origin main
          docker build -t kotague-app .
          docker stop kotague-container || true
          docker rm kotague-container || true
          docker run -d \
            --name kotague-container \
            --restart unless-stopped \
            -p 127.0.0.1:3000:3000 \
            kotague-app